version: '3'
services:
  node:
    build: .
    volumes:
      - ./app:/home/node/app/app
    working_dir: /home/node/app
    command: "npm run start"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  redis:  
    image: redis:latest     